services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    restart: unless-stopped
    ports:
      - "${HOST_PORT_8080:-8080}:8080"
    env_file:
      - .env
    volumes:
      - stirling_data:/usr/share/tessdata
      - stirling_config:/configs

volumes:
  stirling_data:
  stirling_config:
