services:
  headscale:
    image: headscale/headscale:latest
    restart: unless-stopped
    command: serve
    ports:
      - "${HOST_PORT_8080:-8093}:8080"
      - "${HOST_PORT_3478:-3478}:3478/udp"
    environment:
      HEADSCALE_SERVER_URL: ${HEADSCALE_SERVER_URL}
    volumes:
      - headscale_data:/var/lib/headscale
      - headscale_config:/etc/headscale

volumes:
  headscale_data:
  headscale_config:
