services:
  ntfy:
    image: binwiederhier/ntfy:latest
    restart: unless-stopped
    command: serve
    ports:
      - "${HOST_PORT_80:-8080}:80"
    volumes:
      - ntfy_cache:/var/cache/ntfy
      - ntfy_etc:/etc/ntfy

volumes:
  ntfy_cache:
  ntfy_etc:
