services:
  healthchecks:
    image: healthchecks/healthchecks:latest
    restart: unless-stopped
    ports:
      - "${HOST_PORT_8000:-8094}:8000"
    env_file:
      - .env
    volumes:
      - healthchecks_data:/data

volumes:
  healthchecks_data:
