services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "${HOST_PORT_80:-80}:80"
      - "${HOST_PORT_443:-443}:443"
      - "${HOST_PORT_81:-81}:81"
    environment:
      DISABLE_IPV6: ${DISABLE_IPV6:-false}
      X_FRAME_OPTIONS: ${X_FRAME_OPTIONS:-deny}
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

volumes:
  npm_data:
  npm_letsencrypt:
