services:
  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "${HOST_PORT_8080:-8080}:8080"
    volumes:
      - searxng_data:/etc/searxng

volumes:
  searxng_data:
