services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ha_config:/config
      - /etc/localtime:/etc/localtime:ro

volumes:
  ha_config:
