services:
  syncthing:
    image: syncthing/syncthing:latest
    restart: unless-stopped
    ports:
      - "${HOST_PORT_8384:-8384}:8384"
      - "${HOST_PORT_22000:-22000}:22000/tcp"
      - "${HOST_PORT_22000_UDP:-22000}:22000/udp"
    volumes:
      - syncthing_data:/var/syncthing

volumes:
  syncthing_data:
